imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    image_cache: "%kernel.root_dir%/../var/images"
    collections:
      - { id: "vd18.digital", image: "vd18.digital.jpg" }
      - { id: "vd17-nova", image: "vd17-nova.jpg" }
      - { id: "mathematica", image: "mathematica.jpg" }
      - { id: "vd17-mainstream", image: "vd17-mainstream.jpg" }
      - { id: "bucherhaltung", image: "bucherhaltung.jpg" }
      - { id: "varia", image: "varia.jpg" }
      - { id: "nordamericana", image: "nordamericana.jpg" }
      - { id: "blumenbachiana", image: "blumenbachiana.jpg" }
      - { id: "zoologica", image: "zoologica.jpg" }
      - { id: "wissenschaftsgeschichte", image: "wissenschaftsgeschichte.jpg" }
      - { id: "sibirica", image: "sibirica.jpg" }
      - { id: "rusdml", image: "rusdml.jpg" }
      - { id: "rezensionszeitschriften", image: "rezensionszeitschriften.jpg" }
      - { id: "juridica", image: "juridica.jpg" }
      - { id: "göttingeruniversitätsgeschichte-gedrucktewerke", image: "göttingeruniversitätsgeschichte-gedrucktewerke.jpg" }
      - { id: "digiwunschbuch", image: "digiwunschbuch.jpg" }
      - { id: "antiquitates.und.archaeologia.archaeo18", image: "antiquitates.und.archaeologia.archaeo18.jpg" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        name:        "gdses"
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.filesystem

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        metsService: "@mets_service"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_solarium:
    endpoints:
        default:
            scheme: http
            host: "%solr_host%"
            port: 80
            path: /gdz2
            core: collection1
            timeout: 5
    clients:
        default:
            endpoints: [default]

subugoe_find:
    default_query: "ismets:true"
    default_sort: "datemodified desc"
    feed_sort: "dateindexed DESC"
    feed_rows: 15
    feed_category: dc
    feed_fields: ["title", "purl", "dateindexed"]
    facets:
        - { title: facetcreator, field: facetcreator }
        - { title: facetpublisher, field: facetpublisher}
        - { title: facetplacepublish, field: facetplacepublish}
        - { title: yearpublish, field: yearpublish, sort: "index"}
        - { title: dc, field: dc}
        - { title: docstrct, field: docstrct}
    hidden:
        - { field: dc, value: archaeo18 }

knp_paginator:
    page_range: 7                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: sliding.html.twig  # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

guzzle:
    clients:
      mets:
        base_url: "http://gdz.sub.uni-goettingen.de/mets/"
      fulltext:
        base_url: "http://gdz.sub.uni-goettingen.de/gdzocr/"
      tiff:
        base_url: "http://gdz.sub.uni-goettingen.de/tiff/"

liip_imagine:
    resolvers:
       default:
          web_path: ~

    driver: imagick
    filter_sets:
        cache: ~
        collections:
            quality: 75
            filters:
                upscale: { min: [640, 640] }
                crop: { start: [0, 0], size: [640, 640] }
