subugoe_find:
    resource: "@SubugoeFindBundle/Controller"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
